ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('user.urls')),
    path('service/', include('service.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf.urls import handler404
from . import views

handler404 = views.custom_page_not_found_view

app_name = 'app_home'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about , name='about' )
]

user/urls.py
from django.urls import path
from . import views

app_name = 'app_user'

urlpatterns = [
    path('login/', views.UserLoginViews.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register' ),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('edit-profile/', views.ProfileUpdateView.as_view(), name='edit-profile'),
    path('password-change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    link = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"Profile of {self.user.username}"


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

class UserCreationFormWithEmail(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Requerido. Coloque su email.')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationFormWithEmail, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email")

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'birth_date', 'link']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'birth_date': forms.DateField(
                widget=forms.DateInput(attrs={
                    'type': 'date',
                    'class': 'form-control'
                }),
            ),
        }

class ProfileChangeForm(ProfileForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'birth_date', 'link']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control', 'value': ''}),
        }

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views import View
from django.contrib.auth.models import User
from django.views.generic import UpdateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import CustomUserChangeForm, UserCreationFormWithEmail, ProfileChangeForm
from django.contrib.auth import logout
from .models import Profile

class UserLoginViews(LoginView):
    template_name = "user/login.html"


class RegisterView(View):
    template_name = "user/register.html"

    def get(self, request):
        form = UserCreationFormWithEmail()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserCreationFormWithEmail(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app_user:login')
        return render(request, self.template_name, {'form': form})

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = 'user/edit-profile.html'
    success_url = reverse_lazy('app_user:edit-profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        profile, created = Profile.objects.get_or_create(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['profile_form'] = ProfileChangeForm(instance=profile)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()  
        
        user_form = self.get_form() 
        profile = Profile.objects.get(user=self.request.user)  
        profile_form = ProfileChangeForm(request.POST, request.FILES, instance=profile)  

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect(self.success_url)
        else:
            print("User form errors:", user_form.errors)
            print("Profile form errors:", profile_form.errors)
            
        return self.render_to_response(
            self.get_context_data(form=user_form, profile_form=profile_form)
        )

class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'user/profile.html'

class CustomPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'user/password_change.html' 
    success_url = reverse_lazy('app_user:profile')  

    def form_valid(self, form):
        return super().form_valid(form)  
     
class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('app_user:login')

user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Your site description here">
    <title>{% block page_title %}Proyecto Final Python{% endblock %}</title>
    <link rel="icon" href="{% static 'user/images/favicon.ico' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        :root {
            --salmon-50: #FFF5F5;
            --salmon-100: #FFE3E3;
            --salmon-200: #FFC9C9;
            --salmon-300: #FFA8A8;
            --salmon-400: #FF8787;
            --salmon-500: #FF6B6B;
            --salmon-600: #FA5252;
            --salmon-700: #F03E3E;
            --salmon-800: #E03131;
            --salmon-900: #C92A2A;
        }
    
        .btn-salmon {
            background-color: var(--salmon-500);
            border-color: var(--salmon-600);
            color: white;
        }
    
        .btn-salmon:hover {
            background-color: var(--salmon-600);
            border-color: var(--salmon-700);
        }
    
        .table-salmon thead {
            background-color: var(--salmon-100);
            color: var(--salmon-900);
        }
    
        .text-salmon {
            color: var(--salmon-700);
        }
    
        .border-salmon {
            border-color: var(--salmon-300) !important;
        }
        form input {
            width: 100%; 
            border-radius: 5px; 
            border: 1px solid #ccc; 
            padding: 10px; 
            box-sizing: border-box; 
        }
        form label{
            font-size: 20px;
        }

        .custom-avatar .file-upload {
            display: none; /* Oculta "Avatar Actualmente" */
        }
        .custom-avatar .clear {
            display: none; /* Oculta el botón "Limpiar" */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'user/images/logo.jpg' %}" alt="" width="30" height="30" class="d-inline-block align-text-top">
            </a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">Sobre mí</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/profile">Usuarios</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/accounts/login">Usuarios</a>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="/service">Solicitud de Servicio</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Hola, {{ user.first_name|default:user.username }}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userMenu">
                                <li><a class="dropdown-item" href="{% url 'app_user:profile' %}">Ver perfil</a></li>
                                <li><a class="dropdown-item" href="{% url 'app_user:edit-profile' %}">Editar perfil</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item text-danger" href="{% url 'app_user:logout' %}">Cerrar sesión</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="btn btn-salmon" href="{% url 'app_user:login' %}">Iniciar sesión</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-4">
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}{% endblock content %}
    </div>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container text-center">
            <span class="text-muted">© {% now "Y" %} Verónica Frías</span>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

user/templates/user/edit-profile.html
{% extends "user/base.html" %}

{% block page_title %}Proyecto Final Python - Editar Perfil{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card border-salmon">
            <div class="card-header bg-light">
                <h2 class="text-center text-salmon mb-0">Editar Perfil</h2>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field }}
                        {% if field.errors %}
                        <div class="alert alert-danger mt-1">
                            {{ field.errors }}
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <a href="{% url 'app_user:password_change' %}">Cambiar contraseña</a>
                    
                    <h3>Perfil Adicional</h3>
                    {% for field in profile_form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {% if field.name == "avatar" %}
                            {% if field.value %}
                                <div class="mb-2">
                                    <img src="{{ field.value.url }}" alt="Avatar" style="max-width: 150px; height: auto; border: 1px solid #ddd; border-radius: 5px;">
                                </div>
                            {% endif %}
                            <input type="file" name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-control">
                        {% elif field.name == 'birth_date' %}
                        <input type="date" name="{{ field.name }}" id="{{ field.id_for_label }}" value="{{ field.value|date:'Y-m-d' }}" class="form-control">
                        {% else %}
                            {{ field }}
                        {% endif %}
                        {% if field.errors %}
                            <div class="alert alert-danger mt-1">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    
                    <div class="text-center">
                        <button type="submit" class="btn btn-salmon">Actualizar Perfil</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/login.html
{% extends "user/base.html" %}

{% block page_title %}Proyecto Final Python - Inicio de sesión{% endblock %}

{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm border-salmon">
                <div class="card-header bg-salmon text-salmon">
                    <h3 class="mb-0">
                        <i class="bi bi-person-plus me-2"></i>Inicio de sesión
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="mb-3 position-relative">
                                <label for="{{ field.id_for_label }}" class="form-label text-salmon d-block">
                                    {{ field.label }}
                                </label>
                                <div class="input-group">
                                    {{ field }}
                                    {% if field.name == 'password' %}
                                        <button type="button" 
                                                onclick="togglePasswordVisibility('{{ field.id_for_label }}', this)" 
                                                style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%); background: none; border: none; padding: 0;">
                                            <i class="bi bi-eye text-salmon"></i>
                                        </button>
                                    {% endif %}
                                </div>
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ field.errors|striptags }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-grid mb-3">
                            <button type="submit" class="btn btn-salmon">
                                <i class="bi bi-save me-2"></i>Iniciar Sesión
                            </button>
                        </div>
                        <div class="text-center">
                            <a href="{% url 'app_user:register' %}" class="text-salmon">¿No estás registrado? Regístrate aquí</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block scripts %}
<script>
    function togglePasswordVisibility(inputId, button) {
        const inputField = document.getElementById(inputId);
        const icon = button.querySelector('i');
    
        if (inputField.type === "password") {
            inputField.type = "text";
            icon.classList.remove('bi-eye');
            icon.classList.add('bi-eye-slash');
        } else {
            inputField.type = "password";
            icon.classList.remove('bi-eye-slash');
            icon.classList.add('bi-eye');
        }
    }
</script>
{% endblock scripts %}

user/templates/user/password_change.html
{% extends "user/base.html" %}

{% block page_title %}Cambiar Contraseña{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card border-salmon">
            <div class="card-header bg-light">
                <h2 class="text-center text-salmon mb-0">Cambiar Contraseña</h2>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center mt-3">
                        <button type="submit" class="btn btn-salmon">Actualizar Contraseña</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/profile.html
{% extends "user/base.html" %}
{% load static %}

{% block page_title %}Proyecto Final Python - Perfil{% endblock %}

{% block content %}
<div class="container">
    <h1 class="text-salmon text-center">Bienvenido/a, {{ user.username }}</h1>
    <div class="row">
        <div class="col-md-6">
            <p><strong class="text-salmon">Usuario:</strong> {{ user.username }}</p>
            <p><strong class="text-salmon">Email:</strong> {{ user.email }}</p>
            <p><strong class="text-salmon">Nombre:</strong> {{ user.first_name }}</p>
            <p><strong class="text-salmon">Apellido:</strong> {{ user.last_name }}</p>
            <p><strong class="text-salmon">Fecha de nacimiento:</strong> {{ user.profile.birth_date }}</p>
            <p><strong class="text-salmon">Link:</strong> <a href={{ user.profile.link }} target="_blanck">{{ user.profile.link }}</a></p>
        </div>
        <div class="col-md-6">
            {% if user.profile.avatar %}
                <img src="{{ user.profile.avatar.url }}" alt="Avatar" style="max-width: 250px; height: auto; border-radius: 5px;">
            {% else %}
                <img src="{% static 'user/images/avatar.png' %}" alt="Avatar" style="max-width: 250px; height: auto; border-radius: 5px;">
            {% endif %}
        </div>
        <div class="col-12">
            <p><strong class="text-salmon">Biografía:</strong> {{ user.profile.bio}}</p>
        </div>
    </div>
    <a href="{% url 'app_user:logout' %}" class="btn btn-danger">Cerrar sesión</a>
</div>
{% endblock %}

user/templates/user/register.html
{% extends "user/base.html" %}

{% block page_title %}Proyecto Final Python - Registro{% endblock %}

{% block content %}

<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-sm border-salmon">
                <div class="card-header bg-salmon text-salmon">
                    <h3 class="mb-0">
                        <i class="bi bi-person-plus me-2"></i>Registro
                    </h3>
                </div>
                <div class="card-body">
                    <form method="post" class="needs-validation" novalidate>
                        {% csrf_token %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label text-salmon d-block">
                                    {{ field.label }}
                                </label>
                                <div class="input-group">
                                    {{ field }}
                                    {% if field.name == 'password1' or field.name == 'password2' %}
                                        <button type="button" 
                                                onclick="togglePasswordVisibility('{{ field.id_for_label }}', this)" 
                                                style="position: absolute; right: 10px; top: 50%; transform: translateY(-50%); background: none; border: none; padding: 0;">
                                            <i class="bi bi-eye text-salmon"></i>
                                        </button>
                                    {% endif %}
                                </div>
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {{ field.errors|striptags }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-grid mb-3">
                            <button type="submit" class="btn btn-salmon">
                                <i class="bi bi-save me-2"></i>Registrarme
                            </button>
                        </div>
                        <div class="text-center">
                            <a href="{% url 'app_user:login' %}" class="text-salmon">¿Ya estás registrado? Inicie sesión aquí</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

{% block scripts %}
<script>
    function togglePasswordVisibility(inputId, button) {
    const inputField = document.getElementById(inputId);
    const icon = button.querySelector('i');

    if (inputField.type === "password") {
        inputField.type = "text";
        icon.classList.remove('bi-eye');
        icon.classList.add('bi-eye-slash');
    } else {
        inputField.type = "password";
        icon.classList.remove('bi-eye-slash');
        icon.classList.add('bi-eye');
    }
}
</script>
{% endblock scripts %}